# Generated by Django 3.0.7 on 2020-06-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='StoryCardsImage',
        ),
    ]
