# Generated by Django 2.2.3 on 2020-06-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0002_auto_20200625_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='weight',
        ),
        migrations.AddField(
            model_name='storycards',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
