# Generated by Django 2.2.3 on 2020-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_api', '0004_auto_20200626_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storycards',
            options={'ordering': ['weight']},
        ),
        migrations.AlterField(
            model_name='storycards',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='status',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usertagweitage',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
